context:
  version: 0.10.6

package:
  name: ripgrep-all
  version: ${{ version }}

source:
  url: https://github.com/phiresky/ripgrep-all/archive/v${{ version }}.tar.gz
  sha256: 06cd619ad6638be206266a77fdf11034dc2dc15d97b3a057b0d6280a17334680

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  run:
    - fzf
    - ripgrep

tests:
  - script:
      - rga --help

about:
  license: AGPL-3.0-or-later
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Wrapper around ripgrep that adds multiple rich file types
  homepage: https://github.com/phiresky/ripgrep-all
  repository: https://github.com/phiresky/ripgrep-all

extra:
  recipe-maintainers:
    - danielnachun
